name: Update TryHackMe Badge

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: "Intruder1001"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
